version: '3'
services:
  php-apache:
    # restart: always
    build:
      context: ./sys/php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./sys/logs/apache2:/var/log/apache2
      - ./sys/tmp:/tmp
    env_file:
      - ./sys/database.env
  
  mariadb:
    image: mariadb
    # restart: always
    volumes:
        - ./sys/db:/var/lib/mysql
        - ./sys/logs/mariadb:/var/log/mysql
    ports:
        - 3306:3306
    env_file:
        - ./sys/database.env
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mariadb
    # restart: always
    ports:
        - "2292:80"
    volumes:
        - /sessions
    links:
        - mariadb